spring.application.name=event-gateway
server.port=8080
account.service.url=http://account-service:8081
management.otlp.enabled=false
management.otlp.metrics.enabled=false
management.otlp.traces.enabled=false
management.metrics.export.otlp.enabled=false
